---
- name: Install list of packages
  apt: name={{item}} state=installed
  with_items:
       - php-gd
       - php-dom
       - php-mcrypt
       - php-curl
       - php-intl
       - php-mbstring
       - php-zip
       - php-bcmath
       - php-soap

- name: Set repo.magento.com composer keys
  shell: 'composer config --global http-basic.repo.magento.com  b2f5cba61c010a8eb9e563dc7f031db2 842ab5320d751c878cdc488f3e5ddf6a'
  environment:
    HOME: "/root"

- name: download magento with composer
  shell: 'composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.2.7 {{ magento_document_root }}'
  environment:
    HOME: "/root"

- name: Run Magento Installer
  command: 'php bin/magento setup:install --language="en_US" --timezone="{{ tz }}" --db-host={{ mysql_host_ip }} --db-name={{ magento_db_name }} --db-user={{ magento_db_user }} --db-password={{ magento_db_password }} --base-url=http://{{ magento_vhost_domain }}  --use-rewrites="1"  --admin-firstname={{ magento_admin_fname }} --admin-lastname={{ magento_admin_lname }} --admin-email={{ magento_admin_email }} --admin-user={{ magento_admin_user }} --admin-password={{ magento_admin_pass }} --currency=USD'
  args:
    chdir: "{{ magento_document_root }}"

- name: Configure File Level Permissions
  command: 'find . -type f -exec chmod 644 {} ";"'
  args:
    chdir: '{{ magento_document_root }}'
  register: file_perm_change
  changed_when: file_perm_change.stdout

- name: Configure Directory Level Permissions
  command: 'find . -type d -exec chmod 755 {} ";"'
  args:
    chdir: '{{ magento_document_root }}'
  register: file_perm_change
  changed_when: file_perm_change.stdout

- name: Configure File and Directory Ownership
  command: 'chown -R {{ magento_sftp_user }}:{{ nginx_vhost_user }} {{ magento_document_root }}'
  args:
    chdir: '{{ magento_document_root }}'
  register: file_perm_change
  changed_when: file_perm_change.stdout

- name: Create Cron Job
  cron:
    name: "Magento Cron Script"
    user: '{{ magento_sftp_user }}'
    minute: "*/5"
    job: '/bin/sh {{ magento_document_root }}/cron.sh >/dev/null 2>&1'
    state: present

- name: get magento crypt key
  shell: grep -i key {{ magento_document_root }}/app/etc/env.php | awk '{print $3}' | tr -d "',"
  register: grep_output
  ignore_errors: true

- debug:
    var: grep_output.stdout

- name: get frontname
  shell: grep -i front {{ magento_document_root }}/app/etc/env.php | awk '{print $3}' | tr -d "',"
  register: grep_output2
  ignore_errors: true

- debug:
    var: grep_output2.stdout

- name: move over env.php template
  template:
    src: 'Common/env.php.j2'
    dest: '{{ magento_document_root }}/app/etc/env.php'

- name: Start Redis
  service:
    name: redis-server
    state: started
