---
- name: Install PHP
  yum:
    name: php73-cli
    state: present

- name: Install PHP-FPM
  yum:
    name: php73-fpm
    state: present

- name: Include RedHat Vars
  include_vars: RedHat.yml

- name: Install other packages
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ phpfpm_pkgs }}'
