---
- name: Include RedHat Vars
  include_vars: RedHat.yml

- name: Install PHP packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_modules }}"

- name: ensure /opt/pecl exists
  file:
    path: /opt/pecl
    state: directory
    mode: '0755'

- name: download pecl
  get_url:
    url: http://pear.php.net/go-pear.phar
    dest: /opt/pecl/go-pear.phar

- name: Install pecl
  shell: php /opt/pecl/go-pear.phar
  args:
    executable: /bin/bash

- name: Install mcrypt
  shell: pecl install mcrypt-1.0.2
  args:
    executable: /bin/bash

- name: enable mcrypt extension
  lineinfile:
    path: /etc/php.ini
    insertafter: EOF
    line: extension=mcrypt.so
