---
- name: enable remi
  command: yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
  args:
    warn: no

- name: disable php54
  command: yum-config-manager --disable remi-php54
  args:
    warn: no

- name: enable php73
  command: yum-config-manager --enable remi-php72
  args:
    warn: no

- name: Include RedHat Vars
  include_vars: RedHat.yml

- name: Install PHP packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_modules }}"
