---
- name: Install IUS repository - CentOS
  yum:
    name: 'https://repo.ius.io/ius-release-el7.rpm'
  when: ansible_distribution == 'CentOS'

- name: Install IUS repository
  yum:
    name: 'https://repo.ius.io/ius-release-el7.rpm'
  when: ansible_distribution == 'RedHat'
