---
- name: Install LSyncD
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  - lua
  - lua-devel
  - pkgconfig
  - gcc
  - asciidoc
  - lsyncd

- name: Create defaults
  template:
    src: 'Common/lsyncd.j2'
    dest: '/etc/sysconfig/lsyncd'
